### PR TITLE
query template to retrieve binary interaction partners

### PR DESCRIPTION
**Pull request by bill-baumgartner**
This pull request consists of a query template that can be used to retrieve interacting partners for an input protein identifier. This template retrieved binary interactions specifically, i.e. interactions involving only 2 proteins. I'd be happy to go over the query with you. Please let me know if you have any questions.

### CODE REVIEW

**Comment by sinistral** [comment]
This looks good.  Do you not think its worth adding any kind of test case, even just for syntactic validation?  I assume that you've run this through the CLI.

**Comment by ekwhite** [comment]
Looks good to me, all.  I'll merge in the morning if none of you does before then.  Thanks!  Stay warm.

**Comment by bill-baumgartner** [comment]
I did run the query through the CLI to make sure it works. As for a test case, I'm not sure it's worth the effort for the reasons we have discussed before, most notably the fact that the test case could easily become out of date if the underlying KR changes.

**Comment by croeder** [comment]
That's got to be the first time I've heard someone avoid writing a test 
because it might find an issue.

**Pull request merged**
